# Generated by Django 3.1.5 on 2021-03-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
