# Generated by Django 3.1.5 on 2021-03-05 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0009_post_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='blog',
        ),
    ]
