# Generated by Django 3.1.5 on 2021-03-17 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
